name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1

    - name: Build and test
      run: |
        go test ./...
        go build -o simple-go-api ./cmd/simple-go-api

  hom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1

    - name: Build and test
      run: |
        go test ./...
        go build -o simple-go-api ./cmd/simple-go-api

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: | 
        docker build -t eronbetine/simple-go-api:hom .
        docker push eronbetine/simple-go-api:hom
